### ISSUE TITLE
JSON payload explanation 

### ISSUE THREAD

**Issue by martonbaranyai** [rkeeperhun/CRM_Doc#2]
Hello!

After woo commerce purchase, the restaurant needs the booking details uploaded to rkeeper.

is this the correct endpoint? 

https://endpoint.ucs.hu/wp-json/vendor/v1/postorder/<restaurant_id>

could you please explain what the JSON request should contain, and in terms of IDs, where can the correct ones be found?

thanks a lot!

**Comment by avatarf** [comment]
Hi @martonbaranyai 👋 

In short, yes, that's the right URL endpoint!

Longer:
I'm pretty sure you're looking for the other repository and documentation. This repo is about UCS's [CRM system](https://github.com/rkeeperhun/CRM_Doc). The other one is about the [UCS's endpoint](https://github.com/rkeeperhun/Endpoint_Doc/) system to post orders.
Here is the specific part form that documentation: [POST order](https://github.com/rkeeperhun/Endpoint_Doc/blob/master/vendor_api_doc.md)
